// Agentes añadidos con el orquestador Kairo: visión, edición de imagen,
// variaciones, contenido social con imagen, resúmenes y razonamiento.
import { agent, instructions, S } from "./_helpers";

export default [
  agent({
    id: "vision-analyst",
    name: "Vision Analyst",
    description: "Mira la imagen que adjuntes y la describe: contenido, texto visible, estilo y detalles relevantes para tu pregunta.",
    category: "image",
    color: "turquesa",
    model: { prefer: "free", allowFallback: true },
    input: { label: "¿Qué quieres saber de la imagen?", placeholder: "¿Qué pone en este cartel? ¿Qué mejorarías del diseño?", image: "required" },
    instructions: instructions("Eres analista visual. Respondes sobre la imagen con precisión."),
    stages: [
      { id: "analyzing", label: "Vision", kind: "tool", tool: "vision_describe", from: "input" },
      { id: "generating", label: "Answer", kind: "llm", prompt: "Pregunta:\n{{input}}\n\nDescripción de la imagen (modelo de visión):\n{{stage.analyzing}}\n\nResponde a la pregunta basándote solo en lo que se ve." },
    ],
    capabilities: ["Descripción de imágenes", "Texto visible", "Crítica de diseño"],
  }),
  agent({
    id: "image-editor",
    name: "Image Editor",
    description: "Crea una nueva versión de la imagen que adjuntes según tus instrucciones (estilo, ambiente, colores…).",
    category: "image",
    color: "morado",
    input: { label: "¿Cómo quieres cambiarla?", placeholder: "Conviértela en acuarela con tonos cálidos", image: "required" },
    instructions: instructions("Eres editor de imagen. Traduces instrucciones de edición a un prompt visual preciso."),
    stages: [
      { id: "planning", label: "Prompting", kind: "llm", maxTokens: 220, prompt: "Instrucciones de edición:\n{{input}}\n\nEscribe en inglés un único prompt de imagen (máx. 60 palabras) que describa el resultado final deseado. Solo el prompt." },
      { id: "generating", label: "Editing", kind: "tool", tool: "image_edit", from: "planning" },
    ],
    capabilities: ["Imagen → imagen", "Cambio de estilo", "Conserva la composición"],
  }),
  agent({
    id: "image-variations",
    name: "Image Variations",
    description: "Crea una variación de la imagen que adjuntes manteniendo su idea principal.",
    category: "image",
    color: "rosa",
    input: { label: "¿Qué debe cambiar?", placeholder: "Otra paleta de colores", image: "required" },
    instructions: instructions("Eres director de arte."),
    stages: [
      { id: "planning", label: "Prompting", kind: "llm", maxTokens: 200, prompt: "Petición:\n{{input}}\n\nEscribe en inglés un prompt corto (máx. 50 palabras) para una variación de la imagen. Solo el prompt." },
      { id: "generating", label: "Variation", kind: "tool", tool: "image_variation", from: "planning" },
    ],
    capabilities: ["Variaciones", "Misma idea, nuevo resultado"],
  }),
  agent({
    id: "social-post-creator",
    name: "Social Post Creator",
    description: "Escribe un post listo para publicar y genera la imagen que lo acompaña.",
    category: "social",
    color: "naranja",
    input: { label: "¿Sobre qué es el post?", placeholder: "Lanzamiento de nuestra app de recetas en Instagram" },
    instructions: instructions("Eres community manager. Escribes posts claros, con gancho y adaptados a la red social."),
    stages: [
      { id: "planning", label: "Copy", kind: "llm", maxTokens: 600, prompt: "Encargo:\n{{input}}\n\nEscribe el post (gancho, cuerpo breve, llamada a la acción y 3-5 hashtags). Termina con una línea que empiece por PROMPT: con un prompt de imagen en inglés para acompañarlo." },
      { id: "generating", label: "Visual", kind: "tool", tool: "image_generate", from: "planning" },
    ],
    capabilities: ["Copy + imagen", "Hashtags", "Adaptado a cada red"],
  }),
  agent({
    id: "summarizer",
    name: "Summarizer",
    description: "Resume textos largos o páginas web en puntos clave, con la conclusión primero.",
    category: "productivity",
    color: "verde",
    input: { label: "Texto o URL a resumir", placeholder: "Pega el texto o una URL pública" },
    instructions: instructions("Eres experto en síntesis."),
    stages: [
      S.web(),
      { id: "generating", label: "Summarizing", kind: "llm", prompt: "Material:\n{{input}}\n\nPáginas leídas (si había URLs):\n{{stage.reading}}\n\nResume: conclusión en una frase, 5-7 puntos clave y, si aplica, próximos pasos." },
    ],
    capabilities: ["TL;DR", "Puntos clave", "Lee URLs públicas"],
  }),
  agent({
    id: "math-solver",
    name: "Math & Logic Solver",
    description: "Resuelve problemas de matemáticas y lógica paso a paso con un modelo de razonamiento.",
    category: "general",
    color: "azul",
    model: { prefer: "free", allowFallback: true, capability: "reasoning" },
    input: { label: "Problema", placeholder: "Si invierto 1.000 € al 4 % anual compuesto, ¿cuánto tendré en 7 años?" },
    instructions: instructions("Eres profesor de matemáticas. Resuelves paso a paso y compruebas el resultado."),
    stages: [{ id: "generating", label: "Reasoning", kind: "llm", prompt: "Problema:\n{{input}}\n\nResuélvelo paso a paso, verifica el resultado y da la respuesta final destacada." }],
    capabilities: ["Paso a paso", "Modelos de razonamiento abiertos", "Verificación"],
  }),
];
